BaseUrl = "http://fatestigma.github.io"
LanguageCode = "zh-CN"
title = "Gallifrey"
paginate = 5
DisqusShortname = "fatestigma"
Copyright = "All rights reserved - 2016"
canonifyurls = true
hasCJKLanguage = true

[params]
  description = "兴趣驱动型代码狗"
  cover = "images/cover.jpg"
	logo = "images/avatar.jpg"
  author = "Eric"
  authorlocation = "Beijing, China"
  bio = "兴趣驱动型代码狗"
  twitterName = "Fate_Stigma"
  hideHUGOSupport = false

[permalinks]
    post = "/:year/:month/:day/:filename/"

[taxonomies]
	tag = "tags"
	category = "categories"

[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"

